language: php

php:
  - '7.2'

install:
  - composer install

before_script:
  - echo ${TRAVIS_BRANCH} $TRAVIS_BRANCH ${TRAVIS_TAG} $TRAVIS_TAG

script:
  - php tests/test.php

before_deploy:
  - mkdir dist/
  - cp bin dist/ -R
  - cp src dist/ -R
  - cp vendor dist/ -R
  - cp LICENSE dist/
  - cp README.md dist/
  - zip php-enphp-decoder-${TRAVIS_TAG}.zip -r dist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "php-enphp-decoder-${TRAVIS_TAG}.zip"
  skip_cleanup: true
  on:
    tags: true
